import { Product } from '@/types'

export const sampleProducts: Product[] = [
  {
    id: '1',
    slug: 'iphone-15-pro-max',
    name: 'Apple iPhone 15 Pro Max 256GB',
    description: '6.7 инч Super Retina XDR дэлгэц ProMotion-тай, A17 Pro чип, Дэвшилтэт камер систем',
    price: 4499000,
    compareAtPrice: 6499000,
    images: [
      'https://placehold.co/600x600/0ea5e9/white?text=iPhone+15+Pro',
      'https://placehold.co/600x600/0ea5e9/white?text=iPhone+15+Pro+2',
    ],
    category: 'smartphones',
    brand: 'Apple',
    stock: 12,
    rating: 4.8,
    reviewCount: 124,
    featured: true,
    onSale: true,
    isNew: false,
  },
  {
    id: '2',
    slug: 'samsung-galaxy-s24-ultra',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Galaxy AI хиймэл оюун ухаан, 200MP камер, S Pen үзэг, Snapdragon 8 Gen 3 процессор',
    price: 3299000,
    images: ['https://placehold.co/600x600/c026d3/white?text=Galaxy+S24'],
    category: 'smartphones',
    brand: 'Samsung',
    stock: 8,
    rating: 4.7,
    reviewCount: 89,
    featured: true,
    isNew: true,
  },
  {
    id: '3',
    slug: 'xiaomi-14-pro',
    name: 'Xiaomi 14 Pro 512GB',
    description: 'Snapdragon 8 Gen 3 процессор, Leica камер, 120W хурдан цэнэглэгч',
    price: 1899000,
    images: ['https://placehold.co/600x600/22c55e/white?text=Xiaomi+14'],
    category: 'smartphones',
    brand: 'Xiaomi',
    stock: 15,
    rating: 4.6,
    reviewCount: 67,
    featured: true,
  },
  {
    id: '4',
    slug: 'macbook-air-m2',
    name: 'MacBook Air 13" M2 256GB',
    description: 'Apple M2 чип, 13.6 инч Liquid Retina дэлгэц, 18 цаг хүртэл батарей',
    price: 5299000,
    compareAtPrice: 6499000,
    images: ['https://placehold.co/600x600/0ea5e9/white?text=MacBook+Air'],
    category: 'laptops',
    brand: 'Apple',
    stock: 5,
    rating: 4.9,
    reviewCount: 156,
    onSale: true,
  },
  {
    id: '5',
    slug: 'airpods-pro-2',
    name: 'AirPods Pro 2 дугаар үе',
    description: 'Идэвхтэй дуу намсгах, Дасан зохицох ил тод байдал, Орон зайн аудио',
    price: 399000,
    images: ['https://placehold.co/600x600/0ea5e9/white?text=AirPods+Pro'],
    category: 'accessories',
    brand: 'Apple',
    stock: 25,
    rating: 4.7,
    reviewCount: 234,
  },
  {
    id: '6',
    slug: 'ipad-pro-11',
    name: 'iPad Pro 11" M2 128GB',
    description: 'Apple M2 чип, 11 инч Liquid Retina дэлгэц, Apple Pencil дэмжлэг',
    price: 2999000,
    images: ['https://placehold.co/600x600/0ea5e9/white?text=iPad+Pro'],
    category: 'tablets',
    brand: 'Apple',
    stock: 10,
    rating: 4.8,
    reviewCount: 98,
    isNew: true,
  },
  {
    id: '7',
    slug: 'apple-watch-series-9',
    name: 'Apple Watch Series 9 GPS 45мм',
    description: 'Байнга асаалттай Retina дэлгэц, S9 чип, Давхар товшилтын жестүр',
    price: 1299000,
    images: ['https://placehold.co/600x600/0ea5e9/white?text=Apple+Watch'],
    category: 'watches',
    brand: 'Apple',
    stock: 18,
    rating: 4.6,
    reviewCount: 178,
  },
  {
    id: '8',
    slug: 'lenovo-thinkpad-x1',
    name: 'Lenovo ThinkPad X1 Carbon 11 дүгээр үе',
    description: 'Intel Core i7 процессор, 16GB RAM санах ой, 512GB SSD, 14" WUXGA дэлгэц',
    price: 4599000,
    images: ['https://placehold.co/600x600/737373/white?text=ThinkPad'],
    category: 'laptops',
    brand: 'Lenovo',
    stock: 6,
    rating: 4.5,
    reviewCount: 45,
  },
]

export const categories = [
  { id: '1', slug: 'smartphones', name: 'Ухаалаг утас', productCount: 120 },
  { id: '2', slug: 'tablets', name: 'Таблет', productCount: 45 },
  { id: '3', slug: 'laptops', name: 'Зөөврийн компьютер', productCount: 78 },
  { id: '4', slug: 'watches', name: 'Ухаалаг цаг', productCount: 32 },
  { id: '5', slug: 'accessories', name: 'Дагалдах хэрэгсэл', productCount: 200 },
]

export const brands = [
  { id: '1', slug: 'apple', name: 'Apple' },
  { id: '2', slug: 'samsung', name: 'Samsung' },
  { id: '3', slug: 'xiaomi', name: 'Xiaomi' },
  { id: '4', slug: 'huawei', name: 'Huawei' },
  { id: '5', slug: 'lenovo', name: 'Lenovo' },
]

